### ISSUE TITLE
java.lang.NoClassDefFoundError: com.kevalpatel2106.emoticongifkeyboard.internal.emoticon.EmoticonDbHelper

### ISSUE THREAD

**Issue by kirby510** [kevalpatel2106/EmoticonGIFKeyboard#6]
Hi, I faced this issue after build my app with the library. 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.pspimobile, PID: 21685
                                                                java.lang.NoClassDefFoundError: com.kevalpatel2106.emoticongifkeyboard.internal.emoticon.EmoticonDbHelper
                                                                    at com.kevalpatel2106.emoticongifkeyboard.internal.emoticon.EmoticonGridFragment.getEmoticonsList(EmoticonGridFragment.java:153)
                                                                    at com.kevalpatel2106.emoticongifkeyboard.internal.emoticon.EmoticonGridFragment.onViewCreated(EmoticonGridFragment.java:96)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                    at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
                                                                    at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                                    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                                                                    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.support.v7.widget.LinearLayoutCompat.measureChildBeforeLayout(LinearLayoutCompat.java:1374)
                                                                    at android.support.v7.widget.LinearLayoutCompat.measureVertical(LinearLayoutCompat.java:658)
                                                                    at android.support.v7.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:549)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                    at android.view.View.measure(View.java:20151)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:20151)
                                                                	at android.view.ViewGroup.measureChildWithMargins(ViewGrou

I did "Clean Project" and "Rebuild Project" in Android Studio 3.1 Canary 3, and it's doesn't help. Did I left out anything?

**Comment by buckydroid** [comment]
Same problem

**Comment by meethdjain** [comment]
Hi @kevalpatel2106 
Great library 
I'm facing the same issue, Can you help out here ?

**Comment by meethdjain** [comment]
@kirby510 & @buckydroid 

It's working fine now
Add the following dependencies 
compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
compile 'com.github.bumptech.glide:glide:3.8.0'

**Comment by kirby510** [comment]
Thanks a lot, I will try again later on.

**Comment by kirby510** [comment]
It's working... As conclusion I added this in gradle: 

implementation 'com.github.bumptech.glide:glide:3.8.0'
implementation 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
implementation 'com.squareup.retrofit2:retrofit:2.3.0'

Thanks a lot @meethdjain for your guidance. :)
