### ISSUE TITLE
Retrofit 

### ISSUE THREAD

**Issue by tusharuit25** [kevalpatel2106/EmoticonGIFKeyboard#9]
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:321)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:833)
                                                                          Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/Retrofit$Builder;
                                                                             at com.kevalpatel2106.gifpack.giphy.GiphyGifProvider.getTrendingGifs(GiphyGifProvider.java:112)
                                                                             at com.kevalpatel2106.emoticongifkeyboard.internal.gif.GifFragment$TrendingGifTask.doInBackground(GifFragment.java:215)
                                                                             at com.kevalpatel2106.emoticongifkeyboard.internal.gif.GifFragment$TrendingGifTask.doInBackground(GifFragment.java:201)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:307)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:833)

**Comment by WebShaper** [comment]
Have a similar problem. 
https://github.com/kevalpatel2106/EmoticonGIFKeyboard/issues/20
